b=1
try:
    a==2
except NameError, error:
    print error, "error is caused"

